[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
thiserror = { workspace = true }
salsa = { workspace = true }
derive-new = { workspace = true }